language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - 'npm install npm@1.4.28 -g && npm install codeclimate-test-reporter -g'
addons:
  code_climate:
    repo_token: a24608d3ae651be9ee90c7713499c4243d19bab20f15ada39fc3d53b59010a86
after_script:
  - 'npm run gen-coverage && cat coverage/lcov.info | codeclimate-test-reporter'
